export const PROFILE = {
    SUCCESS: "PROFILE_SUCCESS",
    ERROR: "PROFILE_ERROR",
    LOADING: "PROFILE_LOADING",
};

export const SNIPPET = {
    SUCCESS: "SNIPPET_SUCCESS",
    ERROR: "SNIPPET_ERROR",
    LOADING: "SNIPPET_LOADING",
    CLEAR: "SNIPPET_CLEAR",
};

export const MENTORS = {
    SUCCESS: "MENTORS_SUCCESS",
    ERROR: "MENTORS_ERROR",
    LOADING: "MENTORS_LOADING",
};

export const CODERS = {
    SUCCESS: "CODERS_SUCCESS",
    ERROR: "CODERS_ERROR",
    LOADING: "CODERS_LOADING",
};
